# Generated by Django 5.1.7 on 2025-03-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='conversion',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connect',
            name='mineral',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='connect',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='connect',
            name='price',
            field=models.CharField(max_length=12),
        ),
    ]
