# Generated by Django 5.1.7 on 2025-03-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(blank=True, default='', max_length=900, null=True)),
                ('file', models.FileField(upload_to='document/')),
            ],
        ),
    ]
