# Generated by Django 5.1.7 on 2025-03-25 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPoliticalRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(blank=True, default='', max_length=1900, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='NigeriaMineralDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mineral', models.CharField(max_length=150)),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=1900, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='state/')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.geopoliticalregion')),
            ],
        ),
    ]
