# Generated by Django 5.1.7 on 2025-03-25 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_geopoliticalregion_alter_contactus_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nigeriamineraldeposit',
            old_name='mineral',
            new_name='minerals',
        ),
        migrations.AlterField(
            model_name='nigeriamineraldeposit',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.geopoliticalregion'),
        ),
        migrations.AlterField(
            model_name='nigeriamineraldeposit',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
