# Generated by Django 5.1.7 on 2025-03-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_mineral_nigeriamineraldeposit_minerals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nigeriamineraldeposit',
            name='image',
            field=models.ImageField(default='state/Topaz-169707.jpg', upload_to='state/'),
        ),
    ]
