# Generated by Django 5.1.7 on 2025-03-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_nigeriamineraldeposit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nigeriamineraldeposit',
            name='note',
            field=models.TextField(blank=True, default='', max_length=1900, null=True),
        ),
    ]
