# Generated by Django 5.1.7 on 2025-03-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_nigeriamineraldeposit_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minerals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='', max_length=1900, null=True)),
                ('photo', models.ImageField(default='pit/OIP.jpg', upload_to='pit/')),
            ],
        ),
    ]
